version: '2'
services:
     
  kafka11-mock:
    build:
       context: docker-kafka11
    environment:
# on windows systems, change with your own ip. On linux this address should work.
     - ADVERTISED_HOST=172.17.0.1
    ports:
     - "2181:2181"
     - "9092:9092"  
     
  # services with 'depends_on' cannot be extended       
  mock:
    container_name: cqrs-mock-data-generator
    image: cqrs-mock-data-generator
    environment:
     - servers=kafka11-mock:9092
     - producer.sleep.ms=100
     #- main=SingleRunSampleProducer
     - main=InfiniteSampleProducer
     - singlerun.numitems=50
    ports:
     - "9000:9000"  
    depends_on: 
     - kafka11-mock 
    #logging:
    #  driver: none
    
